@file:Suppress("unused")

package org.openrndr.extra.color.presets

import org.openrndr.color.ColorRGBa
import org.openrndr.color.rgb

// Extended colors from
// https://www.w3.org/TR/css-color-3/#svg-color

// Basic colors can be found at
// https://github.com/openrndr/openrndr/blob/master/openrndr-color/src/commonMain/kotlin/org/openrndr/color/ColorRGBa.kt

val ColorRGBa.Companion.ALICE_BLUE              by lazy { rgb("#F0F8FF") }
val ColorRGBa.Companion.ANTIQUE_WHITE           by lazy { rgb("#FAEBD7") }
val ColorRGBa.Companion.AQUA                    by lazy { rgb("#00FFFF") }
val ColorRGBa.Companion.AQUAMARINE              by lazy { rgb("#7FFFD4") }
val ColorRGBa.Companion.AZURE                   by lazy { rgb("#F0FFFF") }
val ColorRGBa.Companion.BEIGE                   by lazy { rgb("#F5F5DC") }
val ColorRGBa.Companion.BISQUE                  by lazy { rgb("#FFE4C4") }
val ColorRGBa.Companion.BLANCHED_ALMOND         by lazy { rgb("#FFEBCD") }
val ColorRGBa.Companion.BLUE_VIOLET             by lazy { rgb("#8A2BE2") }
val ColorRGBa.Companion.BROWN                   by lazy { rgb("#A52A2A") }
val ColorRGBa.Companion.BURLY_WOOD              by lazy { rgb("#DEB887") }
val ColorRGBa.Companion.CADET_BLUE              by lazy { rgb("#5F9EA0") }
val ColorRGBa.Companion.CHARTREUSE              by lazy { rgb("#7FFF00") }
val ColorRGBa.Companion.CHOCOLATE               by lazy { rgb("#D2691E") }
val ColorRGBa.Companion.CORAL                   by lazy { rgb("#FF7F50") }
val ColorRGBa.Companion.CORNFLOWER_BLUE         by lazy { rgb("#6495ED") }
val ColorRGBa.Companion.CORN_SILK               by lazy { rgb("#FFF8DC") }
val ColorRGBa.Companion.CRIMSON                 by lazy { rgb("#DC143C") }
val ColorRGBa.Companion.DARK_BLUE               by lazy { rgb("#00008B") }
val ColorRGBa.Companion.DARK_CYAN               by lazy { rgb("#008B8B") }
val ColorRGBa.Companion.DARK_GOLDEN_ROD         by lazy { rgb("#B8860B") }
val ColorRGBa.Companion.DARK_GRAY               by lazy { rgb("#A9A9A9") }
val ColorRGBa.Companion.DARK_GREY               by lazy { rgb("#A9A9A9") }
val ColorRGBa.Companion.DARK_GREEN              by lazy { rgb("#006400") }
val ColorRGBa.Companion.DARK_KHAKI              by lazy { rgb("#BDB76B") }
val ColorRGBa.Companion.DARK_MAGENTA            by lazy { rgb("#8B008B") }
val ColorRGBa.Companion.DARK_OLIVE_GREEN        by lazy { rgb("#556B2F") }
val ColorRGBa.Companion.DARK_ORANGE             by lazy { rgb("#FF8C00") }
val ColorRGBa.Companion.DARK_ORCHID             by lazy { rgb("#9932CC") }
val ColorRGBa.Companion.DARK_RED                by lazy { rgb("#8B0000") }
val ColorRGBa.Companion.DARK_SALMON             by lazy { rgb("#E9967A") }
val ColorRGBa.Companion.DARK_SEA_GREEN          by lazy { rgb("#8FBC8F") }
val ColorRGBa.Companion.DARK_SLATE_BLUE         by lazy { rgb("#483D8B") }
val ColorRGBa.Companion.DARK_SLATE_GRAY         by lazy { rgb("#2F4F4F") }
val ColorRGBa.Companion.DARK_SLATE_GREY         by lazy { rgb("#2F4F4F") }
val ColorRGBa.Companion.DARK_TURQUOISE          by lazy { rgb("#00CED1") }
val ColorRGBa.Companion.DARK_VIOLET             by lazy { rgb("#9400D3") }
val ColorRGBa.Companion.DEEP_PINK               by lazy { rgb("#FF1493") }
val ColorRGBa.Companion.DEEP_SKY_BLUE           by lazy { rgb("#00BFFF") }
val ColorRGBa.Companion.DIM_GRAY                by lazy { rgb("#696969") }
val ColorRGBa.Companion.DIM_GREY                by lazy { rgb("#696969") }
val ColorRGBa.Companion.DODGER_BLUE             by lazy { rgb("#1E90FF") }
val ColorRGBa.Companion.FIREBRICK               by lazy { rgb("#B22222") }
val ColorRGBa.Companion.FLORAL_WHITE            by lazy { rgb("#FFFAF0") }
val ColorRGBa.Companion.FOREST_GREEN            by lazy { rgb("#228B22") }
val ColorRGBa.Companion.FUCHSIA                 by lazy { rgb("#FF00FF") }
val ColorRGBa.Companion.GAINSBORO               by lazy { rgb("#DCDCDC") }
val ColorRGBa.Companion.GHOST_WHITE             by lazy { rgb("#F8F8FF") }
val ColorRGBa.Companion.GOLD                    by lazy { rgb("#FFD700") }
val ColorRGBa.Companion.GOLDENROD               by lazy { rgb("#DAA520") }
val ColorRGBa.Companion.GREY                    by lazy { rgb("#808080") }
val ColorRGBa.Companion.GREEN_YELLOW            by lazy { rgb("#ADFF2F") }
val ColorRGBa.Companion.HONEYDEW                by lazy { rgb("#F0FFF0") }
val ColorRGBa.Companion.HOT_PINK                by lazy { rgb("#FF69B4") }
val ColorRGBa.Companion.INDIAN_RED              by lazy { rgb("#CD5C5C") }
val ColorRGBa.Companion.INDIGO                  by lazy { rgb("#4B0082") }
val ColorRGBa.Companion.IVORY                   by lazy { rgb("#FFFFF0") }
val ColorRGBa.Companion.KHAKI                   by lazy { rgb("#F0E68C") }
val ColorRGBa.Companion.LAVENDER                by lazy { rgb("#E6E6FA") }
val ColorRGBa.Companion.LAVENDER_BLUSH          by lazy { rgb("#FFF0F5") }
val ColorRGBa.Companion.LAWN_GREEN              by lazy { rgb("#7CFC00") }
val ColorRGBa.Companion.LEMON_CHIFFON           by lazy { rgb("#FFFACD") }
val ColorRGBa.Companion.LIGHT_BLUE              by lazy { rgb("#ADD8E6") }
val ColorRGBa.Companion.LIGHT_CORAL             by lazy { rgb("#F08080") }
val ColorRGBa.Companion.LIGHT_CYAN              by lazy { rgb("#E0FFFF") }
val ColorRGBa.Companion.LIGHT_GOLDEN_ROD_YELLOW by lazy { rgb("#FAFAD2") }
val ColorRGBa.Companion.LIGHT_GRAY              by lazy { rgb("#D3D3D3") }
val ColorRGBa.Companion.LIGHT_GREY              by lazy { rgb("#D3D3D3") }
val ColorRGBa.Companion.LIGHT_GREEN             by lazy { rgb("#90EE90") }
val ColorRGBa.Companion.LIGHT_PINK              by lazy { rgb("#FFB6C1") }
val ColorRGBa.Companion.LIGHT_SALMON            by lazy { rgb("#FFA07A") }
val ColorRGBa.Companion.LIGHT_SEA_GREEN         by lazy { rgb("#20B2AA") }
val ColorRGBa.Companion.LIGHT_SKY_BLUE          by lazy { rgb("#87CEFA") }
val ColorRGBa.Companion.LIGHT_SLATE_GRAY        by lazy { rgb("#778899") }
val ColorRGBa.Companion.LIGHT_SLATE_GREY        by lazy { rgb("#778899") }
val ColorRGBa.Companion.LIGHT_STEEL_BLUE        by lazy { rgb("#B0C4DE") }
val ColorRGBa.Companion.LIGHT_YELLOW            by lazy { rgb("#FFFFE0") }
val ColorRGBa.Companion.LIME                    by lazy { rgb("#00FF00") }
val ColorRGBa.Companion.LIME_GREEN              by lazy { rgb("#32CD32") }
val ColorRGBa.Companion.LINEN                   by lazy { rgb("#FAF0E6") }
val ColorRGBa.Companion.MAROON                  by lazy { rgb("#800000") }
val ColorRGBa.Companion.MEDIUM_AQUAMARINE       by lazy { rgb("#66CDAA") }
val ColorRGBa.Companion.MEDIUM_BLUE             by lazy { rgb("#0000CD") }
val ColorRGBa.Companion.MEDIUM_ORCHID           by lazy { rgb("#BA55D3") }
val ColorRGBa.Companion.MEDIUM_PURPLE           by lazy { rgb("#9370DB") }
val ColorRGBa.Companion.MEDIUM_SEA_GREEN        by lazy { rgb("#3CB371") }
val ColorRGBa.Companion.MEDIUM_SLATE_BLUE       by lazy { rgb("#7B68EE") }
val ColorRGBa.Companion.MEDIUM_SPRING_GREEN     by lazy { rgb("#00FA9A") }
val ColorRGBa.Companion.MEDIUM_TURQUOISE        by lazy { rgb("#48D1CC") }
val ColorRGBa.Companion.MEDIUM_VIOLET_RED       by lazy { rgb("#C71585") }
val ColorRGBa.Companion.MIDNIGHT_BLUE           by lazy { rgb("#191970") }
val ColorRGBa.Companion.MINT_CREAM              by lazy { rgb("#F5FFFA") }
val ColorRGBa.Companion.MISTY_ROSE              by lazy { rgb("#FFE4E1") }
val ColorRGBa.Companion.MOCCASIN                by lazy { rgb("#FFE4B5") }
val ColorRGBa.Companion.NAVAJO_WHITE            by lazy { rgb("#FFDEAD") }
val ColorRGBa.Companion.NAVY                    by lazy { rgb("#000080") }
val ColorRGBa.Companion.OLD_LACE                by lazy { rgb("#FDF5E6") }
val ColorRGBa.Companion.OLIVE                   by lazy { rgb("#808000") }
val ColorRGBa.Companion.OLIVE_DRAB              by lazy { rgb("#6B8E23") }
val ColorRGBa.Companion.ORANGE                  by lazy { rgb("#FFA500") }
val ColorRGBa.Companion.ORANGE_RED              by lazy { rgb("#FF4500") }
val ColorRGBa.Companion.ORCHID                  by lazy { rgb("#DA70D6") }
val ColorRGBa.Companion.PALE_GOLDEN_ROD         by lazy { rgb("#EEE8AA") }
val ColorRGBa.Companion.PALE_GREEN              by lazy { rgb("#98FB98") }
val ColorRGBa.Companion.PALE_TURQUOISE          by lazy { rgb("#AFEEEE") }
val ColorRGBa.Companion.PALE_VIOLET_RED         by lazy { rgb("#DB7093") }
val ColorRGBa.Companion.PAPAYA_WHIP             by lazy { rgb("#FFEFD5") }
val ColorRGBa.Companion.PEACH_PUFF              by lazy { rgb("#FFDAB9") }
val ColorRGBa.Companion.PERU                    by lazy { rgb("#CD853F") }
val ColorRGBa.Companion.PLUM                    by lazy { rgb("#DDA0DD") }
val ColorRGBa.Companion.POWDER_BLUE             by lazy { rgb("#B0E0E6") }
val ColorRGBa.Companion.PURPLE                  by lazy { rgb("#800080") }
val ColorRGBa.Companion.ROSY_BROWN              by lazy { rgb("#BC8F8F") }
val ColorRGBa.Companion.ROYAL_BLUE              by lazy { rgb("#4169E1") }
val ColorRGBa.Companion.SADDLE_BROWN            by lazy { rgb("#8B4513") }
val ColorRGBa.Companion.SALMON                  by lazy { rgb("#FA8072") }
val ColorRGBa.Companion.SANDY_BROWN             by lazy { rgb("#F4A460") }
val ColorRGBa.Companion.SEA_GREEN               by lazy { rgb("#2E8B57") }
val ColorRGBa.Companion.SEASHELL                by lazy { rgb("#FFF5EE") }
val ColorRGBa.Companion.SIENNA                  by lazy { rgb("#A0522D") }
val ColorRGBa.Companion.SILVER                  by lazy { rgb("#C0C0C0") }
val ColorRGBa.Companion.SKY_BLUE                by lazy { rgb("#87CEEB") }
val ColorRGBa.Companion.SLATE_BLUE              by lazy { rgb("#6A5ACD") }
val ColorRGBa.Companion.SLATE_GRAY              by lazy { rgb("#708090") }
val ColorRGBa.Companion.SLATE_GREY              by lazy { rgb("#708090") }
val ColorRGBa.Companion.SNOW                    by lazy { rgb("#FFFAFA") }
val ColorRGBa.Companion.SPRING_GREEN            by lazy { rgb("#00FF7F") }
val ColorRGBa.Companion.STEEL_BLUE              by lazy { rgb("#4682B4") }
val ColorRGBa.Companion.BLUE_STEEL              by lazy { rgb("#4682B4") }
val ColorRGBa.Companion.TAN                     by lazy { rgb("#D2B48C") }
val ColorRGBa.Companion.TEAL                    by lazy { rgb("#008080") }
val ColorRGBa.Companion.THISTLE                 by lazy { rgb("#D8BFD8") }
val ColorRGBa.Companion.TOMATO                  by lazy { rgb("#FF6347") }
val ColorRGBa.Companion.TURQUOISE               by lazy { rgb("#40E0D0") }
val ColorRGBa.Companion.VIOLET                  by lazy { rgb("#EE82EE") }
val ColorRGBa.Companion.WHEAT                   by lazy { rgb("#F5DEB3") }
val ColorRGBa.Companion.WHITE_SMOKE             by lazy { rgb("#F5F5F5") }
val ColorRGBa.Companion.YELLOW_GREEN            by lazy { rgb("#9ACD32") }
