import org.openrndr.application
import org.openrndr.color.ColorRGBa
import org.openrndr.extra.osc.OSC

/**
 * Demonstrates how to expose three variable to be controlled by Chataigne
 * (two Double variables and a ColorRGBa).
 *
 * The variables control the color, opacity and radius of a circle
 * rendered at the center of the screen.
 *
 * The values can be generated by Chataigne itself, or by other hardware
 * or software supported by Chataigne (for instance, a joystick, a gamepad,
 * a Kinect camera, etc.)
 *
 * See the related Chataigne project under the `resources` folder.
 */
fun main() = application {
    configure {
        width = 500
        height = 500
    }

   /* Find the Chataigne example project in /resources */
    class SceneVariables : ChataigneOSC(OSC(portIn = 9005, portOut = 12001)) {
        val myRadius: Double by DoubleChannel("/myRadius")
        val myOpacity: Double by DoubleChannel("/myOpacity")
        val myColor: ColorRGBa by ColorChannel("/myColor")
    }

    program {
        val animation = SceneVariables()

        extend {
            animation.update(seconds)

            drawer.fill = animation.myColor.opacify(animation.myOpacity)
            drawer.circle(width/2.0, height/2.0, animation.myRadius * 250)
        }
    }
}