name: Build
on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./orx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v6
        with:
          path: ./orx

      - name: Checkout OPENRNDR repository
        run: |
          BRANCH_NAME=${{ github.head_ref || github.ref_name }}
          echo "Checking for branch $BRANCH_NAME in openrndr/openrndr"
          if git ls-remote --exit-code --heads https://github.com/openrndr/openrndr.git "$BRANCH_NAME" > /dev/null; then
            echo "Branch $BRANCH_NAME found in openrndr/openrndr"
            echo "OPENRNDR_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV
          else
            echo "Branch $BRANCH_NAME not found in openrndr/openrndr, falling back to master"
            echo "OPENRNDR_BRANCH=master" >> $GITHUB_ENV
          fi
        working-directory: .

      - name: Checkout OPENRNDR
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          repository: openrndr/openrndr
          ref: ${{ env.OPENRNDR_BRANCH }}
          path: ./openrndr

      - name: Test glxinfo
        run: |
          sudo apt-get update
          sudo apt-get install -y mesa-utils xvfb
          xvfb-run glxinfo

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build OPENRNDR
        working-directory: ./openrndr
        run: ./gradlew publishToMavenLocal snapshot

      - name: Build ORX
        run: ./gradlew build -Popenrndr.application.backend=application-glfw

      - name: Collect screenshots without errors
        run: xvfb-run ./gradlew collectScreenshots -Popenrndr.application.backend=application-glfw
